# Generated by Django 5.2 on 2025-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('correct_answer', models.CharField(max_length=10)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
    ]
